#
#
#

spring.application.name=verisimilar-api
spring.profiles.active=dev
server.port=8085

# MUST BE SET WITH USERS/KEYS FOR API KEY AUTHENTICATION
spring.config.import=optional:file:../../parent/config/verisimilar/api/api.yaml

generator.bulk.max-lines=1000
generator.bulk.outfile.dir=/tmp/verisimilar/outfiles/

logging.level.root=INFO
logging.level.com.reneekbartlett=INFO

# For fastest setup (test/dev), use h2.
spring.datasource.url=jdbc:h2:mem:rb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=localuser
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.main.banner-mode=off

spring.thymeleaf.enabled=false

spring.threads.virtual.enabled=true

server.error.whitelabel.enabled=false

# actuator: http://localhost:8085/actuator/env
#management.endpoint.env.show-values=ALWAYS
#management.endpoints.web.exposure.include=env,health,info,features,metrics,prometheus